---

- hosts: all
  become: true
  pre_tasks:

  - name: install updates
    tags: always
    package:
      update_cache: yes

- hosts: web_servers
  become: true
  tasks:

  - name: install httpd and php packages
    tags: httpd,php
    package:
      name: 
        - "{{ httpd_package }}"
        - "{{ php_package }}"
      state: latest

  - name: copy default html file for site
    tags: httpd,apache2
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb
    tags: db
    yum:
      name: mariadb-server
      state: latest